### ISSUE TITLE
There seems to be an error in the library

### ISSUE THREAD

**Issue by Masa-74** [metocean/netcdfjs#3]
I'm trying to encode a NetCDF file in Node.js program.
I created a sample code like below.

	var readstream = require('netcdf/fs/readstream');
	var readrandom = require('netcdf/fs/readrandom');
	var netcdf = require('netcdf');
	 
	var file = './examples/WMI_Lear.nc';
	var headerbuffer = readstream(file);
	 
	// Read the header of a NetCDF file 
	netcdf.readheader(headerbuffer, function(header) {
	  console.log(JSON.stringify(header, null, 2));
	  
	  var randombuffer = readrandom(file);
	  
	  // Read a variable 
	  netcdf.readvariable(header, randombuffer, 'lat', function(err, data) {
	    if (err != null) {
	      return console.error(err);
	    }
	    console.log(data);
	  });
	  
	  // Read records 
	  netcdf.readrecords(header, randombuffer, function(err, data) {
	    if (err != null) {
	      return console.error(err);
	    }
	    console.log(data);
	  });
	});

Now, once I run a program, I get an error below.

	C:\app [master +2 ~1 -0 !]> npm start
	
	> spaceapps@1.0.0 start C:\app
	> node server.js
	
	C:\app\node_modules\text-encoding\lib\encoding.js:979
	      throw TypeError('Called as a function. Did you forget \'new\'?');
	      ^
	
	TypeError: Called as a function. Did you forget 'new'?
	    at TypeError (native)
	    at Object.TextDecoder (C:\app\node_modules\text-encoding\lib\encoding.js:979:13)
	    at Object.<anonymous> (C:\app\node_modules\netcdf\util\readbinary.js:4:40)
	    at Module._compile (module.js:413:34)
	    at Object.Module._extensions..js (module.js:422:10)
	    at Module.load (module.js:357:32)
	    at Function.Module._load (module.js:314:12)
	    at Module.require (module.js:367:17)
	    at require (internal/module.js:16:19)
	    at Object.<anonymous> (C:\app\node_modules\netcdf\util\type.js:4:14)
	
	npm ERR! Windows_NT 6.3.9600
	npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v\\nodev5.9.1\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "start"
	npm ERR! node v5.9.1
	npm ERR! npm  v3.8.7
	npm ERR! code ELIFECYCLE
	npm ERR! spaceapps@1.0.0 start: `node server.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the spaceapps@1.0.0 start script 'node server.js'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the spaceapps package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node server.js
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs spaceapps
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls spaceapps
	npm ERR! There is likely additional logging output above.
	
	npm ERR! Please include the following file with any support request:
	npm ERR!     C:\app\npm-debug.log
	C:\app [master +3 ~1 -0 !]>

**Comment by tcoats** [comment]
Hi @Masa-74 thank you for your comment.

`netcdfjs` is not finished. A lot of functionality has been developed, but it needs more development and testing.

If anyone has time to contribute to this project they are more than welcome.
