### ISSUE TITLE
Add maka-io as contributor

### ISSUE THREAD

**Issue by timoxley** [metocean/netcdfjs#5]
So @maka-io has produced and published a `netcdfjs` fork as https://www.npmjs.com/package/rps-netcdf. 

Perhaps it would be better to collaborate rather than dilute effort across multiple repos. 
@metocean, @maka-io would you be willing to work together? @metocean you'd just need to add @maka-io as an github/npm collaborator.

💛

**Comment by timoxley** [comment]
Differences below. @maka-io appears to be making some good build improvements. https://github.com/metocean/netcdfjs/compare/master...maka-io:master?expand=1

**Comment by timoxley** [comment]
Though I'm not sure about bundling `node_modules`  :/

**Comment by maka-io** [comment]
Oh, did the node_modules get in there! That's not good.

@timoxley @metocean I'd be SUPER happy to collaborate!

**Comment by alpha-beta-soup** [comment]
Sounds like a great idea. I've invited @maka-io to be a collaborator for this project.

**Comment by timoxley** [comment]
👍 💯
